[package]
name = "chim-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
chim-span = { path = "../chim-span" }
chim-error = { path = "../chim-error" }
lasso = "0.7"
logos = "0.14"
smallvec = "1.11"
thiserror = "1.0"
